In [1]:
# List creation
mylist = [123, "vishva"]
print("mylist:", mylist)
print("Type of mylist:", type(mylist))

# List with repeated elements
mylist = [2] * 5
print("Repeated list:", mylist)

# List from tuple
mylist = list((1, "vishva", 6))
print("List from tuple:", mylist)

# Remove element from list
mylist.remove("vishva")  # Removes first occurrence of "vishva"
print("After removing 'vishva':", mylist)

# Delete by index using another list
d = [1, 2, 3, 4, 5]
del d[2]  # Deletes element at index 2
print("List after deleting index 2:", d)

# Modify list element
mylist2 = ["vishva", "abcd"]
print("Original list:", mylist2)
mylist2[0] = "Vishva"
print("Modified list:", mylist2)

# Set creation — corrected
myset = {"vishva", "abcd", "efgh"}
print("Set:", myset)

# Set from string — unique characters only
myset2 = set("abc")
print("Set from string:", myset2)

# Tuple
tup = ("abcd", "efgh", "ijk")
print("Tuple:", tup)

# Dictionary
dic = {1: "abcd", 2: "efgh", 3: "ijk"}
print("Dictionary:", dic)


mylist: [123, 'vishva']
Type of mylist: <class 'list'>
Repeated list: [2, 2, 2, 2, 2]
List from tuple: [1, 'vishva', 6]
After removing 'vishva': [1, 6]
List after deleting index 2: [1, 2, 4, 5]
Original list: ['vishva', 'abcd']
Modified list: ['Vishva', 'abcd']
Set: {'abcd', 'vishva', 'efgh'}
Set from string: {'a', 'c', 'b'}
Tuple: ('abcd', 'efgh', 'ijk')
Dictionary: {1: 'abcd', 2: 'efgh', 3: 'ijk'}


In [2]:
# ------- Set Operations --------

# Create a set
set_1 = {1, 2, 3, 4, 5}
print("Initial set_1:", set_1)

# Add element (5 is already there, so no change)
set_1.add(5)
print("Set after add(5):", set_1)

# Discard element
set_1.discard(2)
print("Set after discard(2):", set_1)

# Pop from another set
set_2 = {1, 2, 3, 4, 5}
print("Initial set_2:", set_2)
val = set_2.pop()
print("Popped value from set_2:", val)
print("Set_2 after pop():", set_2)

# Clear sets
set_1.clear()
print("Set_1 after clear():", set_1)

set_2.clear()
print("Set_2 after clear():", set_2)


# ------- Dictionary Operations --------

# Create dictionary
dic = {1: "vishva", 2: "abcd", 3: "efgh"}
print("Initial dictionary:", dic)

# Add new key-value pair
dic[4] = "ijk"
print("After adding key 4:", dic)

# Modify existing key
dic[1] = "bala"
print("After modifying key 1:", dic)

# Delete key 4
del dic[4]
print("After deleting key 4:", dic)

# Pop last inserted item
val = dic.popitem()
print("Popped item:", val)
print("Dictionary after popitem():", dic)


Initial set_1: {1, 2, 3, 4, 5}
Set after add(5): {1, 2, 3, 4, 5}
Set after discard(2): {1, 3, 4, 5}
Initial set_2: {1, 2, 3, 4, 5}
Popped value from set_2: 1
Set_2 after pop(): {2, 3, 4, 5}
Set_1 after clear(): set()
Set_2 after clear(): set()
Initial dictionary: {1: 'vishva', 2: 'abcd', 3: 'efgh'}
After adding key 4: {1: 'vishva', 2: 'abcd', 3: 'efgh', 4: 'ijk'}
After modifying key 1: {1: 'bala', 2: 'abcd', 3: 'efgh', 4: 'ijk'}
After deleting key 4: {1: 'bala', 2: 'abcd', 3: 'efgh'}
Popped item: (3, 'efgh')
Dictionary after popitem(): {1: 'bala', 2: 'abcd'}


In [3]:
import numpy as np
import pandas as pd

# ------- NumPy Operations --------

# 1D array
arr = np.array([1, 2, 3, 4])
print("Array arr:", arr)

# 2D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print("Array arr1:\n", arr1)

# Another 2D array
r2a = np.array([[3, 2], [1, 4]])
print("Array r2a:\n", r2a)

b = np.array([[5, 5], [7, 8]])
print("Array b:\n", b)

# Add 1 to every element of b
print("b + 1:\n", b + 1)

# Subtract 1 from every element of b
print("b - 1:\n", b - 1)

# Sum of all elements in b
print("Sum of all elements in b:", b.sum())

# Data type of b
print("Data type of b:", b.dtype)

# Create array with float type
arr3 = np.array([[7, 8], [3, 9]], dtype=np.float64)
print("Array arr3:\n", arr3)

# Another array for addition
arr4 = np.array([[1, 2], [3, 4]])
print("Array arr4:\n", arr4)

# Add two arrays
sum_result = np.add(arr3, arr4)
print("Sum of arr3 and arr4:\n", sum_result)


Array arr: [1 2 3 4]
Array arr1:
 [[1 2 3]
 [4 5 6]]
Array r2a:
 [[3 2]
 [1 4]]
Array b:
 [[5 5]
 [7 8]]
b + 1:
 [[6 6]
 [8 9]]
b - 1:
 [[4 4]
 [6 7]]
Sum of all elements in b: 25
Data type of b: int64
Array arr3:
 [[7. 8.]
 [3. 9.]]
Array arr4:
 [[1 2]
 [3 4]]
Sum of arr3 and arr4:
 [[ 8. 10.]
 [ 6. 13.]]
